### ISSUE TITLE
Can you provide a pretrained model?

### ISSUE THREAD

**Issue by TonyLiangJunsheng** [pielet/HairNet#1]

**Comment by pielet** [comment]
You can find it in HairNet/network/experiments/ckpt/
: )

**Comment by TonyLiangJunsheng** [comment]
There is only  a ckpt-7840.meta file, but the corresponding ckpt-7840.ckpt file is missing.

**Comment by pielet** [comment]
Sorry, I've uploaded it to BaiduYun. You can download it from the link in readme now.

**Comment by TonyLiangJunsheng** [comment]
Thank you very much :)

**Comment by VikasSoni1** [comment]
I cant download the model from link on baidu. Can i please get a google drive link instead if possible?
Thanks
